// angular-app/src/app/products/products.component.ts
import { Component, OnInit } from "@angular/core";
import { faSave, faTools } from "@fortawesome/free-solid-svg-icons";
import { NgbModal } from "@ng-bootstrap/ng-bootstrap";

import { ProductService } from "../product.service";

import { Product } from "../product";
import { ParametersComponent } from "../parameters/parameters.component";

@Component({
  selector: "app-products",
  templateUrl: "./products.component.html",
  styleUrls: ["./products.component.scss"]
})
export class ProductsComponent implements OnInit {
  products: Product[];
  faSave = faSave;
  faTools = faTools;
  saved = true;

  constructor(
    public productService: ProductService,
    private modalService: NgbModal
  ) {}

  ngOnInit() {
    this.productService.subscribeToProducts();
      this.products = this.productService.products;
  }

  handleInputChange(e, p: Product) {
    let products = [...this.products];
    let index = products.indexOf(p);
    const name = e.target.id;
    const value = e.target.value;
    p[name] = value;
    products.splice(index, 1, p);
    this.products = products;
    this.saved = false;
  }

  handleSaveChanges() {
    this.products.forEach(product =>
      this.productService.updateProduct(product)
    );
    this.saved = true;
  }

  deleteProduct(product: Product) {
    this.productService.deleteProduct(product);
    this.products = this.products.filter(p => p.id !== product.id);
  }

  openModal() {
    this.modalService.open(ParametersComponent, {
      size: "sm"
    });
  }
}

<div class="container" style="overflow-x: auto;">
  <h1 class="text-center">
    Ecommerce calculator
  </h1>
  <p>
    <fa-icon
      (click)="handleSaveChanges()"
      size="lg"
      class="float-right m-3"
      [ngClass]="{ blinking: !saved }"
      [icon]="faSave"
    ></fa-icon>
    <fa-icon
      (click)="openModal()"
      class="float-right m-3"
      [icon]="faTools"
    ></fa-icon>
  </p>
  <table class="table table-stripped table-bordered">
    <thead>
      <tr>
        <th>Product</th>
        <th>Cost</th>
        <th>Sell</th>
        <th>Profit</th>
        <th>Rate</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let p of products">
        <td>
          <a id="name" routerLink="form/{{ p.id }}">
            {{ p.name }}
          </a>
          <span
            class="badge badge-danger float-right delete"
            (click)="deleteProduct(p)"
            >Delete</span
          >
        </td>
        <td>
          <input
            [value]="p.cost"
            (change)="handleInputChange($event, p)"
            id="cost"
            min="0"
            type="number"
          />
        </td>
        <td>
          <input
            [value]="p.sell"
            (change)="handleInputChange($event, p)"
            id="sell"
            min="0"
            type="number"
          />
        </td>
        <td>
          <span id="profit">{{ p.profit }}</span>
        </td>
        <td>
          <span id="rate" [ngStyle]="{ color: p.rate >= 10 ? 'green' : 'red' }">
            {{ p.rate }} %
          </span>
        </td>
      </tr>
    </tbody>
  </table>
</div>

// react-app/src/products.jsx
import React, { Component } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTools, faSave } from '@fortawesome/free-solid-svg-icons';
import './Products.css';
import { getProducts, updateProduct } from './productService';

export class Products extends Component {
  state = {
    products: [],
    save: true
  };
  async componentDidMount() {
    this.setState({ products: await getProducts() });
  }

  handleInputChange = (e, p) => {
    let products = [...this.state.products];
    let index = products.indexOf(p);
    const name = e.target.id;
    const value = e.target.value;
    p[name] = value;
    products.splice(index, 1, p);
    this.setState({ products, save: false });
  };

  handleSave = () => {
    this.setState({ save: true });
  };

  render() {
    return (
      <div className="container" style={{ overflowX: 'auto' }}>
        <h3 className="text-center">Ecommerce calculator</h3>
        <FontAwesomeIcon
          className={
            this.state.save ? 'float-right icon' : 'float-right icon blinking'
          }
          icon={faSave}
          onClick={this.handleSave}
        />
        <FontAwesomeIcon className="float-right icon" icon={faTools} />
        <table className="table table-stripped table-bordered">
          <thead>
            <tr>
              <th>Product</th>
              <th>Cost</th>
              <th>Sell</th>
              <th>Profit</th>
              <th>Rate</th>
            </tr>
          </thead>
          <tbody>
            {this.state.products.map(p => (
              <tr key={p.id}>
                <td>
                  <a
                    href={p.href}
                    onClick={() => this.props.onSelectProduct(p)}
                    id="product"
                  >
                    {p.name}
                  </a>
                </td>
                <td>
                  <input
                    value={p.cost}
                    id="cost"
                    type="number"
                    onChange={e => this.handleInputChange(e, p)}
                  />
                </td>
                <td>
                  <input
                    value={p.sell}
                    type="number"
                    id="sell"
                    onChange={e => this.handleInputChange(e, p)}
                  />
                </td>
                <td>
                  <span id="profit">{p.profit}</span>
                </td>
                <td>
                  <span
                    style={{ color: p.rate >= 10 ? 'green' : 'red' }}
                    id="rate"
                  >
                    {p.rate} %
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }
}
