// react-app/src/product-form.jsx
import React, { Component } from 'react';
import { saveProduct, updateProduct } from './productService';
import { Product } from './product';

export class ProductForm extends Component {
  state = {
    product: null
  };
  componentDidMount() {
    let selectedProduct = this.props.selectedProduct;
    console.log(selectedProduct);
    this.initialiseProduct(selectedProduct);
  }

  initialiseProduct(product) {
    if (product) this.setState({ product });
    else this.setState({ product: new Product() });
  }

  handleInputChange = ({ target }) => {
    let product = Object.create(new Product(), { ...this.state.product });
    console.log(product);
    product[target.id] = target.value;
    console.log(product);
    this.setState(product);
  };

  handleSubmit = e => {
    e.preventDefault();
    let { product } = this.state;
    if (product.isNew) saveProduct(product);
    else updateProduct(product);
    this.props.onSubmit(1);
  };

  render() {
    const { product: p } = this.state;
    return (
      <div className="container">
        <h3 className="text-center text-nowrap">Add new product</h3>
        <form onSubmit={this.handleSubmit}>
          <div className="form-group">
            <label htmlFor="name">Product name</label>
            <input
              onChange={this.handleInputChange}
              id="name"
              className="form-control"
              type="text"
              value={p?.name}
            />
          </div>
          <div className="form-group">
            <label htmlFor="url">URL</label>
            <input
              onChange={this.handleInputChange}
              id="url"
              className="form-control"
              type="url"
              value={p?.url}
            />
          </div>
          <input type="submit" className="btn btn-primary" value="Save" />
        </form>
      </div>
    );
  }
}

// angular-app/src/app/product-form/product-form.component.ts
import { NavService } from "./../nav.service";
import { Component, OnInit } from "@angular/core";
import { ProductService } from "../product.service";
import { Product } from "../product";

@Component({
  selector: "app-product-form",
  templateUrl: "./product-form.component.html",
  styleUrls: ["./product-form.component.scss"]
})
export class ProductFormComponent implements OnInit {
  product: Product;
  constructor(
    private productService: ProductService,
    public navService: NavService
  ) {}

  ngOnInit(): void {
    let selectedProduct = this.productService.selectedProduct;
    this.initialiseProduct(selectedProduct);
  }

  initialiseProduct(product?: Product) {
    if (product) this.product = product;
    else this.product = this.productService.selectedProduct = new Product();
  }

  handleSubmit() {
    if (this.product.isNew) this.productService.saveProduct(this.product);
    else this.productService.updateProduct(this.product);
    this.navService.select(1);
  }
}

<div class="container">
  <h3 class=" text-nowrap text-center">
    {{ product.isNew ? "New product" : "Edit product" }}
  </h3>
  <div class="row">
    <div class="col-7"></div>
    <div class="col">
      <button
        (click)="navService.select(1)"
        type="button"
        class="btn btn-info float-right ml-2 mb-2"
      >
        Back
      </button>
      <button
        type="button"
        *ngIf="!product.isNew"
        (click)="initialiseProduct()"
        class="btn btn-primary float-right"
      >
        New product
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <form (ngSubmit)="handleSubmit()">
        <div class="form-group">
          <label htmlFor="name">Product name</label>
          <input
            [(ngModel)]="product.name"
            id="name"
            name="name"
            class="form-control"
            required
            type="text"
          />
        </div>
        <div class="form-group">
          <label htmlFor="url">URL</label>
          <input
            [(ngModel)]="product.url"
            name="url"
            id="url"
            class="form-control"
            type="url"
          />
        </div>
        <ng-container *ngIf="!product.isNew">
          <div class="form-group">
            <label htmlFor="cost">Cost</label>
            <input
              [(ngModel)]="product.cost"
              name="cost"
              id="cost"
              min="0"
              class="form-control"
              type="number"
            />
          </div>
          <div class="form-group">
            <label htmlFor="sell">Sell</label>
            <input
              [(ngModel)]="product.sell"
              name="sell"
              id="sell"
              min="0"
              class="form-control"
              type="number"
            />
          </div>
        </ng-container>
        <div class="text-center">
          <input type="submit" class="btn btn-primary " value="Save" />
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
</div>
